version = 1

[[analyzers]]
name = "scala"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "1.30.0"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/deepsourcelabs/Gigarepo"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "secrets"